<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_dRl-4K0xEeu-2IxxI52J7g" name="AjusteCurricular" author="tonussi-recovery" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_dRl-4a0xEeu-2IxxI52J7g" name="Ajuste Curricular">
      <elements xmi:type="process:Lane" xmi:id="_dRl-4q0xEeu-2IxxI52J7g" name="Den prograd" actor="_jJ680K00EeuvSOVcsXUZdQ">
        <elements xmi:type="process:StartEvent" xmi:id="_dRl-460xEeu-2IxxI52J7g" name="Iniciar1" outgoing="_dRl--K0xEeu-2IxxI52J7g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dRl-5K0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dRl-5a0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dRl-5q0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_dRl-560xEeu-2IxxI52J7g" name="Gerar portaria de ajuste curricular" outgoing="_HEc8YK0zEeuvSOVcsXUZdQ" incoming="_dRl--K0xEeu-2IxxI52J7g" actor="_jJ680K00EeuvSOVcsXUZdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dRl-6K0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dRl-6a0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dRl-6q0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q5zrAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q5z7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q50LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q50bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemanal" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemanal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q50rAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q507AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemanal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q51LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q51bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q51rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q517AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTeoricaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTeoricaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q52LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q52bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTeoricaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q52rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q527AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q53LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q53bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaPraticaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaPraticaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q53rAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q537AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaPraticaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q54LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q54bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q54rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q547AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q55LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q55bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q55rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q557AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q56LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q56bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nroPortaria" content="portariaAjusteCurricularInput?.nroPortaria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q56rAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q567AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNroPortaria">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q57LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q57bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q57rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q577AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDisciplina" content="portariaAjusteCurricularInput?.codigoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q58LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q58bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q58rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q587AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q59LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q59bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeProReitorGrad" content="//import org.bonitasoft.engine.api.IdentityAPI;&#xA;//IdentityAPI identity = apiAccessor.getIdentityAPI();&#xA;//return identity.getActiveUsersInRole(&quot;pro-reitor-graduacao&quot;);&#xA;portariaAjusteCurricularInput?.nomeProReitorGrad&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1DhekLBIEeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q597AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeProReitorGrad">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q5-LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q5-bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q5-rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q5-7AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDepartamento" content="portariaAjusteCurricularInput?.codigoDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q5_LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q5_bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q5_rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q5_7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6ALAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6AbAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDisciplina" content="portariaAjusteCurricularInput?.nomeDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6ArAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6A7AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6BLAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6BbAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6BrAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6B7AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.descricaoEmenta" content="portariaAjusteCurricularInput?.descricaoEmenta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6CLAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6CbAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDescricaoEmenta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6CrAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6C7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6DLAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6DbAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDepartamento" content="portariaAjusteCurricularInput?.nomeDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6DrAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6D7AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6ELAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6EbAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6ErAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6E7AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.dataLancamento" content="portariaAjusteCurricularInput?.dataLancamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6FLAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6FbAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDataLancamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6FrAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6F7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6GLAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6GbAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.assinaturaDigital" content="portariaAjusteCurricularInput?.assinaturaDigital" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8l4nULBJEeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6G7AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setAssinaturaDigital">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ffav0LA7EeuUGry6jKu2kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ffav0bA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_f5I3YLA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ffav0rA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput.nroProcessoCriacaoDisciplina" content="portariaAjusteCurricularInput?.nroProcessoCriacaoDisciplina&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ubYIALEbEeuf0e7JypUhFQ" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ffav07A7EeuUGry6jKu2kw" type="JAVA_METHOD" expression="setNroProcessoCriacaoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dRl-660xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dRl-7K0xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dRl-7a0xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dRl-7q0xEeu-2IxxI52J7g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dRl-760xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dRl-8K0xEeu-2IxxI52J7g">
            <targetForm xmi:type="expression:Expression" xmi:id="__mBKAK00EeuvSOVcsXUZdQ" name="portariaAjusteCurricularForm" content="b76dd7dc-405e-47db-839a-695c76ea5411" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dRl-8q0xEeu-2IxxI52J7g">
            <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5wLAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" dataReference="portariaAjusteCurricular">
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5wbAuEeutU43AkzFzNw" name="cargaHorariaTotalSemanal"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5wrAuEeutU43AkzFzNw" name="cargaHorariaTeoricaSemestral"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5w7AuEeutU43AkzFzNw" name="cargaHorariaPraticaSemestral"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5xLAuEeutU43AkzFzNw" name="cargaHorariaTotalSemestral"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5xbAuEeutU43AkzFzNw" name="nroPortaria"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5xrAuEeutU43AkzFzNw" name="codigoDisciplina"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5x7AuEeutU43AkzFzNw" name="nomeProReitorGrad"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5yLAuEeutU43AkzFzNw" name="codigoDepartamento"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5ybAuEeutU43AkzFzNw" name="nomeDisciplina"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5yrAuEeutU43AkzFzNw" name="descricaoEmenta"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5y7AuEeutU43AkzFzNw" name="nomeDepartamento"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5zLAuEeutU43AkzFzNw" name="dataLancamento"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5zbAuEeutU43AkzFzNw" name="assinaturaDigital" type="BOOLEAN"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_EU5fQLA7EeutU43AkzFzNw" name="nroProcessoCriacaoDisciplina">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_EU5fQbA7EeutU43AkzFzNw"/>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dRl-860xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_acu_sK0zEeuvSOVcsXUZdQ" name="Providenciar portaria no boletim ufsc" outgoing="_enVX4K0zEeuvSOVcsXUZdQ" incoming="_JJpHQK0zEeuvSOVcsXUZdQ" actor="_jJ680K00EeuvSOVcsXUZdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JJbr4a0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JJbr4K0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JJbr4q0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqnrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqn7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqoLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqobAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemanal" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemanal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqorAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqo7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemanal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqpLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqpbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqprAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqp7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTeoricaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTeoricaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqqLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqqbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTeoricaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqqrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqq7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqrLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqrbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaPraticaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaPraticaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqrrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqr7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaPraticaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqsLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqsbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqsrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqs7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqtLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqtbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqtrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqt7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoquLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqubAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nroPortaria" content="portariaAjusteCurricularInput?.nroPortaria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqurAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqu7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNroPortaria">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqvLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqvbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqvrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqv7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDisciplina" content="portariaAjusteCurricularInput?.codigoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqwLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqwbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqwrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqw7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqxLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqxbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeProReitorGrad" content="portariaAjusteCurricularInput?.nomeProReitorGrad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqxrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqx7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeProReitorGrad">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqyLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqybAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqyrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqy7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDepartamento" content="portariaAjusteCurricularInput?.codigoDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqzLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqzbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqzrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqz7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq0LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq0bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDisciplina" content="portariaAjusteCurricularInput?.nomeDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq0rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq07AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq1LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq1bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq1rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq17AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.descricaoEmenta" content="portariaAjusteCurricularInput?.descricaoEmenta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq2LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq2bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDescricaoEmenta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq2rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq27AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq3LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq3bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDepartamento" content="portariaAjusteCurricularInput?.nomeDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq3rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq37AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq4LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq4bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq4rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq47AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.dataLancamento" content="portariaAjusteCurricularInput?.dataLancamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq5LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq5bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDataLancamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq5rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq57AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq6LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq6bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.assinaturaDigital" content="portariaAjusteCurricularInput?.assinaturaDigital" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq6rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq67AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setAssinaturaDigital">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3qga0LA7EeuUGry6jKu2kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3qga0bA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4SCU4LA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3qga0rA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput.nroProcessoCriacaoDisciplina" content="portariaAjusteCurricularInput?.nroProcessoCriacaoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9Iu-ELA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3qga07A7EeuUGry6jKu2kw" type="JAVA_METHOD" expression="setNroProcessoCriacaoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JJcS8K0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JJcS8a0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JJcS8q0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JJcS9K0zEeuvSOVcsXUZdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JJcS860zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_acyDB60zEeuvSOVcsXUZdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_US_MYLEnEeuf0e7JypUhFQ" name="formularioPublicacaoPortaria" content="71146179-cf3b-4144-b0d4-c19d1003e971" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_acyDBq0zEeuvSOVcsXUZdQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_xYoqkLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" dataReference="portariaAjusteCurricular" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqkbAvEeutU43AkzFzNw" name="cargaHorariaTotalSemanal" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqkrAvEeutU43AkzFzNw" name="cargaHorariaTeoricaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqk7AvEeutU43AkzFzNw" name="cargaHorariaPraticaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqlLAvEeutU43AkzFzNw" name="cargaHorariaTotalSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqlbAvEeutU43AkzFzNw" name="nroPortaria" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqlrAvEeutU43AkzFzNw" name="codigoDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoql7AvEeutU43AkzFzNw" name="nomeProReitorGrad" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqmLAvEeutU43AkzFzNw" name="codigoDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqmbAvEeutU43AkzFzNw" name="nomeDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqmrAvEeutU43AkzFzNw" name="descricaoEmenta" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqm7AvEeutU43AkzFzNw" name="nomeDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqnLAvEeutU43AkzFzNw" name="dataLancamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqnbAvEeutU43AkzFzNw" name="assinaturaDigital" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2yplwLA7EeuUGry6jKu2kw" name="nroProcessoCriacaoDisciplina">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_2yqM0LA7EeuUGry6jKu2kw"/>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_acyDCa0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_enODIK0zEeuvSOVcsXUZdQ" name="Fim1" incoming="_enVX4K0zEeuvSOVcsXUZdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_enOqMa0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_enOqMK0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_enOqMq0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ClmygK0zEeuvSOVcsXUZdQ" name="Pro reitor grad" actor="_yPmigK00EeuvSOVcsXUZdQ">
        <elements xmi:type="process:Task" xmi:id="_aH9CgK0zEeuvSOVcsXUZdQ" name="Assinar portaria de ajuste curricular" outgoing="_JJpHQK0zEeuvSOVcsXUZdQ" incoming="_HEc8YK0zEeuvSOVcsXUZdQ" actor="_yPmigK00EeuvSOVcsXUZdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HDyOAK0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HDxm8K0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HDyOAa0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_3OpbvrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opbv7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpbwLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpbwbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemanal" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemanal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpbwrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opbw7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemanal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpbxLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OpbxbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpbxrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opbx7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTeoricaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTeoricaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpbyLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OpbybAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTeoricaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpbyrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opby7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpbzLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpbzbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaPraticaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaPraticaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpbzrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opbz7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaPraticaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb0LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb0bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb0rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb07AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb1LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb1bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb1rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb17AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb2LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb2bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nroPortaria" content="portariaAjusteCurricularInput?.nroPortaria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb2rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb27AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNroPortaria">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb3LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb3bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb3rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb37AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDisciplina" content="portariaAjusteCurricularInput?.codigoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb4LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb4bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb4rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb47AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb5LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb5bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeProReitorGrad" content="portariaAjusteCurricularInput?.nomeProReitorGrad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb5rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb57AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeProReitorGrad">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb6LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb6bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb6rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb67AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDepartamento" content="portariaAjusteCurricularInput?.codigoDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb7LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb7bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb7rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb77AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb8LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb8bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDisciplina" content="portariaAjusteCurricularInput?.nomeDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb8rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb87AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb9LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb9bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb9rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb97AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.descricaoEmenta" content="portariaAjusteCurricularInput?.descricaoEmenta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb-LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb-bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDescricaoEmenta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb-rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb-7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb_LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb_bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDepartamento" content="portariaAjusteCurricularInput?.nomeDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb_rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb_7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpcALAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OpcAbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpcArAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpcA7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.dataLancamento" content="portariaAjusteCurricularInput?.dataLancamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpcBLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OpcBbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDataLancamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpcBrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OpcB7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpcCLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpcCbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.assinaturaDigital" content="portariaAjusteCurricularInput?.assinaturaDigital" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpcCrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OpcC7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setAssinaturaDigital">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_vbYdQLA7EeuUGry6jKu2kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_vbYdQbA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_vykOMLA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_vbYdQrA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput.nroProcessoCriacaoDisciplina" content="portariaAjusteCurricularInput?.nroProcessoCriacaoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_0Jz7QLA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_vbYdQ7A7EeuUGry6jKu2kw" type="JAVA_METHOD" expression="setNroProcessoCriacaoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HDyOAq0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HDyOA60zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HDyOBK0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HDy1EK0zEeuvSOVcsXUZdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HDyOBa0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_aH-3sa0zEeuvSOVcsXUZdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_YmkdYK01EeuvSOVcsXUZdQ" name="formularioAssinaturaPortaria" content="bda36800-1d07-49d5-8a61-c7e0f83f016e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_aH-3sK0zEeuvSOVcsXUZdQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_3OpbsLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" dataReference="portariaAjusteCurricular" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbsbAvEeutU43AkzFzNw" name="cargaHorariaTotalSemanal" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbsrAvEeutU43AkzFzNw" name="cargaHorariaTeoricaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3Opbs7AvEeutU43AkzFzNw" name="cargaHorariaPraticaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbtLAvEeutU43AkzFzNw" name="cargaHorariaTotalSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbtbAvEeutU43AkzFzNw" name="nroPortaria" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbtrAvEeutU43AkzFzNw" name="codigoDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3Opbt7AvEeutU43AkzFzNw" name="nomeProReitorGrad" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbuLAvEeutU43AkzFzNw" name="codigoDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbubAvEeutU43AkzFzNw" name="nomeDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpburAvEeutU43AkzFzNw" name="descricaoEmenta" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3Opbu7AvEeutU43AkzFzNw" name="nomeDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbvLAvEeutU43AkzFzNw" name="dataLancamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbvbAvEeutU43AkzFzNw" name="assinaturaDigital" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_uGV88LA7EeuUGry6jKu2kw" name="nroProcessoCriacaoDisciplina">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_uGV88bA7EeuUGry6jKu2kw"/>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_aH-3s60zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_9Cy_UK00EeuvSOVcsXUZdQ" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria">
        <defaultValue xmi:type="expression:Expression" xmi:id="_9Cy_Ua00EeuvSOVcsXUZdQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_dRl-9K0xEeu-2IxxI52J7g">
        <targetForm xmi:type="expression:Expression" xmi:id="_wd1G8LEmEeuf0e7JypUhFQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_dRl-9q0xEeu-2IxxI52J7g">
        <targetForm xmi:type="expression:Expression" xmi:id="_dRl-960xEeu-2IxxI52J7g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dRl--K0xEeu-2IxxI52J7g" target="_dRl-560xEeu-2IxxI52J7g" source="_dRl-460xEeu-2IxxI52J7g" isDefault="true" conditionType="DECISION_TABLE">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dRl--a0xEeu-2IxxI52J7g"/>
        <condition xmi:type="expression:Expression" xmi:id="_dRl--q0xEeu-2IxxI52J7g" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HEc8YK0zEeuvSOVcsXUZdQ" target="_aH9CgK0zEeuvSOVcsXUZdQ" source="_dRl-560xEeu-2IxxI52J7g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HEdjcK0zEeuvSOVcsXUZdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HEdjca0zEeuvSOVcsXUZdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JJpHQK0zEeuvSOVcsXUZdQ" target="_acu_sK0zEeuvSOVcsXUZdQ" source="_aH9CgK0zEeuvSOVcsXUZdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JJpHQa0zEeuvSOVcsXUZdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JJpuUK0zEeuvSOVcsXUZdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_enVX4K0zEeuvSOVcsXUZdQ" target="_enODIK0zEeuvSOVcsXUZdQ" source="_acu_sK0zEeuvSOVcsXUZdQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_enV-8K0zEeuvSOVcsXUZdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_enV-8a0zEeuvSOVcsXUZdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_jJ680K00EeuvSOVcsXUZdQ" documentation="Técnico em Exercício no DEN PROGRAD" name="tecnico-exercicio-den-prograd" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_yPmigK00EeuvSOVcsXUZdQ" documentation="Pró reitor de graduação" name="pro-reitor-de-graduacao"/>
      <contract xmi:type="process:Contract" xmi:id="_dRl-_K0xEeu-2IxxI52J7g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl-_a0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl-_q0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl-_60xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_AK0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_Aa0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_Aq0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_A60xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_BK0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_Ba0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_Bq0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_B60xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_CK0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_Ca0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_Cq0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_C60xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_dRl_DK0xEeu-2IxxI52J7g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_dRl_Da0xEeu-2IxxI52J7g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_dRl_Dq0xEeu-2IxxI52J7g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_dRl_D60xEeu-2IxxI52J7g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_dRl_EK0xEeu-2IxxI52J7g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_dRl_Ea0xEeu-2IxxI52J7g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_dRl_Eq0xEeu-2IxxI52J7g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_dRl_E60xEeu-2IxxI52J7g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_dRl_FK0xEeu-2IxxI52J7g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_dRl_Fa0xEeu-2IxxI52J7g" type="Process" element="_dRl-4K0xEeu-2IxxI52J7g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_dRl_Fq0xEeu-2IxxI52J7g" type="2007" element="_dRl-4a0xEeu-2IxxI52J7g">
      <children xmi:type="notation:DecorationNode" xmi:id="_dRl_F60xEeu-2IxxI52J7g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_dRl_GK0xEeu-2IxxI52J7g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_dRl_Ga0xEeu-2IxxI52J7g" type="3007" element="_dRl-4q0xEeu-2IxxI52J7g">
          <children xmi:type="notation:DecorationNode" xmi:id="_dRl_Gq0xEeu-2IxxI52J7g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_dRl_G60xEeu-2IxxI52J7g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_dRl_HK0xEeu-2IxxI52J7g" type="3005" element="_dRl-560xEeu-2IxxI52J7g" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dRl_Ha0xEeu-2IxxI52J7g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_Hq0xEeu-2IxxI52J7g" x="89" y="127" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dRl_H60xEeu-2IxxI52J7g" type="3002" element="_dRl-460xEeu-2IxxI52J7g" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_dRl_IK0xEeu-2IxxI52J7g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dRl_Ia0xEeu-2IxxI52J7g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_Iq0xEeu-2IxxI52J7g" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ac0fQK0zEeuvSOVcsXUZdQ" type="3005" element="_acu_sK0zEeuvSOVcsXUZdQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ac1GUK0zEeuvSOVcsXUZdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ac0fQa0zEeuvSOVcsXUZdQ" x="479" y="106" width="196" height="98"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_enPRQK0zEeuvSOVcsXUZdQ" type="3003" element="_enODIK0zEeuvSOVcsXUZdQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_enPRQq0zEeuvSOVcsXUZdQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_enPRQ60zEeuvSOVcsXUZdQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_enPRQa0zEeuvSOVcsXUZdQ" x="753" y="98"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_dRl_I60xEeu-2IxxI52J7g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_dRl_JK0xEeu-2IxxI52J7g" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_dRl_Ja0xEeu-2IxxI52J7g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_dRl_Jq0xEeu-2IxxI52J7g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_J60xEeu-2IxxI52J7g"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Cl5GYK0zEeuvSOVcsXUZdQ" type="3007" element="_ClmygK0zEeuvSOVcsXUZdQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Cl6UgK0zEeuvSOVcsXUZdQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Cl6Uga0zEeuvSOVcsXUZdQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_aIAs4K0zEeuvSOVcsXUZdQ" type="3005" element="_aH9CgK0zEeuvSOVcsXUZdQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_aIBT8K0zEeuvSOVcsXUZdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aIAs4a0zEeuvSOVcsXUZdQ" x="308" y="81" width="204" height="102"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Cl5tcK0zEeuvSOVcsXUZdQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Cl5tca0zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Cl5tcq0zEeuvSOVcsXUZdQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Cl67kK0zEeuvSOVcsXUZdQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Cl5tc60zEeuvSOVcsXUZdQ" x="48" y="250" width="803" height="243"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_dRl_KK0xEeu-2IxxI52J7g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_dRl_Ka0xEeu-2IxxI52J7g" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_dRl_Kq0xEeu-2IxxI52J7g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_dRl_K60xEeu-2IxxI52J7g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_LK0xEeu-2IxxI52J7g" width="826" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_dRl_La0xEeu-2IxxI52J7g"/>
    <edges xmi:type="notation:Connector" xmi:id="_dRl_Lq0xEeu-2IxxI52J7g" type="4001" element="_dRl--K0xEeu-2IxxI52J7g" source="_dRl_H60xEeu-2IxxI52J7g" target="_dRl_HK0xEeu-2IxxI52J7g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dRl_L60xEeu-2IxxI52J7g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dRl_MK0xEeu-2IxxI52J7g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dRl_Ma0xEeu-2IxxI52J7g" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dRl_Mq0xEeu-2IxxI52J7g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HEfYoK0zEeuvSOVcsXUZdQ" type="4001" element="_HEc8YK0zEeuvSOVcsXUZdQ" source="_dRl_HK0xEeu-2IxxI52J7g" target="_aIAs4K0zEeuvSOVcsXUZdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HEf_sK0zEeuvSOVcsXUZdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HEf_sa0zEeuvSOVcsXUZdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HEfYoa0zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HEfYoq0zEeuvSOVcsXUZdQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JJq8cK0zEeuvSOVcsXUZdQ" type="4001" element="_JJpHQK0zEeuvSOVcsXUZdQ" source="_aIAs4K0zEeuvSOVcsXUZdQ" target="_ac0fQK0zEeuvSOVcsXUZdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JJrjgK0zEeuvSOVcsXUZdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JJrjga0zEeuvSOVcsXUZdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JJq8ca0zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JJq8cq0zEeuvSOVcsXUZdQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_enV-8q0zEeuvSOVcsXUZdQ" type="4001" element="_enVX4K0zEeuvSOVcsXUZdQ" source="_ac0fQK0zEeuvSOVcsXUZdQ" target="_enPRQK0zEeuvSOVcsXUZdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_enWmAK0zEeuvSOVcsXUZdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_enWmAa0zEeuvSOVcsXUZdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_enV-860zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_enV-9K0zEeuvSOVcsXUZdQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
