<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_dRl-4K0xEeu-2IxxI52J7g" name="AjusteCurricular" author="tonussi-recovery" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_dRl-4a0xEeu-2IxxI52J7g" name="MODELO AJUSTE CURRICULAR V1.0 (TO-DO)">
      <elements xmi:type="process:Lane" xmi:id="_dRl-4q0xEeu-2IxxI52J7g" name="DOCENTES RESPONSAVEIS" actor="_QfyOILK0EeutJdt5dtTumA">
        <elements xmi:type="process:StartEvent" xmi:id="_dRl-460xEeu-2IxxI52J7g" name="Iniciar1" outgoing="_wTSY0LKwEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dRl-5K0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dRl-5a0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dRl-5q0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_q6nD8LKwEeutJdt5dtTumA" name="T10: Criar proposta de disciplina no sistema siga" outgoing="_G2228LKyEeutJdt5dtTumA" incoming="_wTSY0LKwEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_q6nrAbKwEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_q6nrALKwEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_q6nrArKwEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_q6nrA7KwEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_q6nrBLKwEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_q6nrBbKwEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_q6nrB7KwEeutJdt5dtTumA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_q6nrBrKwEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_Gc5e0LKyEeutJdt5dtTumA" name="T20: Elaborar programa de ensino" outgoing="_H0zs8LKyEeutJdt5dtTumA" incoming="_G2228LKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Gc77ELKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Gc7UALKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Gc77EbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Gc77ErKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Gc77E7KyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Gc77FLKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Gc77FrKyEeutJdt5dtTumA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Gc77FbKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ClmygK0zEeuvSOVcsXUZdQ" name="TECNICOS DEN PROGRAD" actor="_jJ680K00EeuvSOVcsXUZdQ">
        <elements xmi:type="process:Task" xmi:id="_dRl-560xEeu-2IxxI52J7g" name="T30: Gerar portaria de ajuste curricular" outgoing="_HEc8YK0zEeuvSOVcsXUZdQ" incoming="_H0zs8LKyEeutJdt5dtTumA" actor="_jJ680K00EeuvSOVcsXUZdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dRl-6K0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dRl-6a0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dRl-6q0xEeu-2IxxI52J7g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q5zrAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q5z7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q50LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q50bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemanal" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemanal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q50rAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q507AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemanal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q51LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q51bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q51rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q517AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTeoricaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTeoricaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q52LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q52bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTeoricaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q52rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q527AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q53LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q53bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaPraticaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaPraticaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q53rAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q537AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaPraticaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q54LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q54bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q54rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q547AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q55LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q55bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q55rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q557AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q56LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q56bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nroPortaria" content="portariaAjusteCurricularInput?.nroPortaria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q56rAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q567AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNroPortaria">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q57LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q57bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q57rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q577AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDisciplina" content="portariaAjusteCurricularInput?.codigoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q58LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q58bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q58rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q587AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q59LAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q59bAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeProReitorGrad" content="//import org.bonitasoft.engine.api.IdentityAPI;&#xA;//IdentityAPI identity = apiAccessor.getIdentityAPI();&#xA;//return identity.getActiveUsersInRole(&quot;pro-reitor-graduacao&quot;);&#xA;portariaAjusteCurricularInput?.nomeProReitorGrad&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1DhekLBIEeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q597AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeProReitorGrad">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q5-LAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q5-bAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q5-rAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q5-7AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDepartamento" content="portariaAjusteCurricularInput?.codigoDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q5_LAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q5_bAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q5_rAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q5_7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6ALAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6AbAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDisciplina" content="portariaAjusteCurricularInput?.nomeDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6ArAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6A7AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6BLAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6BbAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6BrAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6B7AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.descricaoEmenta" content="portariaAjusteCurricularInput?.descricaoEmenta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6CLAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6CbAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDescricaoEmenta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6CrAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6C7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6DLAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6DbAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDepartamento" content="portariaAjusteCurricularInput?.nomeDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6DrAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6D7AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6ELAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6EbAuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6ErAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6E7AuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.dataLancamento" content="portariaAjusteCurricularInput?.dataLancamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_g9Q6FLAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6FbAuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDataLancamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_g9Q6FrAuEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_g9Q6F7AuEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_g9Q6GLAuEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_g9Q6GbAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput.assinaturaDigital" content="portariaAjusteCurricularInput?.assinaturaDigital" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_8l4nULBJEeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_g9Q6G7AuEeutU43AkzFzNw" type="JAVA_METHOD" expression="setAssinaturaDigital">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ffav0LA7EeuUGry6jKu2kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ffav0bA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_f5I3YLA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ffav0rA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput.nroProcessoCriacaoDisciplina" content="portariaAjusteCurricularInput?.nroProcessoCriacaoDisciplina&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ubYIALEbEeuf0e7JypUhFQ" name="portariaAjusteCurricularInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ffav07A7EeuUGry6jKu2kw" type="JAVA_METHOD" expression="setNroProcessoCriacaoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dRl-660xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dRl-7K0xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dRl-7a0xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dRl-7q0xEeu-2IxxI52J7g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dRl-760xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dRl-8K0xEeu-2IxxI52J7g">
            <targetForm xmi:type="expression:Expression" xmi:id="__mBKAK00EeuvSOVcsXUZdQ" name="portariaAjusteCurricularForm" content="b76dd7dc-405e-47db-839a-695c76ea5411" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dRl-8q0xEeu-2IxxI52J7g">
            <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5wLAuEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" dataReference="portariaAjusteCurricular">
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5wbAuEeutU43AkzFzNw" name="cargaHorariaTotalSemanal"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5wrAuEeutU43AkzFzNw" name="cargaHorariaTeoricaSemestral"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5w7AuEeutU43AkzFzNw" name="cargaHorariaPraticaSemestral"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5xLAuEeutU43AkzFzNw" name="cargaHorariaTotalSemestral"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5xbAuEeutU43AkzFzNw" name="nroPortaria"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5xrAuEeutU43AkzFzNw" name="codigoDisciplina"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5x7AuEeutU43AkzFzNw" name="nomeProReitorGrad"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5yLAuEeutU43AkzFzNw" name="codigoDepartamento"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5ybAuEeutU43AkzFzNw" name="nomeDisciplina"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5yrAuEeutU43AkzFzNw" name="descricaoEmenta"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5y7AuEeutU43AkzFzNw" name="nomeDepartamento"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5zLAuEeutU43AkzFzNw" name="dataLancamento"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_g9Q5zbAuEeutU43AkzFzNw" name="assinaturaDigital" type="BOOLEAN"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_EU5fQLA7EeutU43AkzFzNw" name="nroProcessoCriacaoDisciplina">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_EU5fQbA7EeutU43AkzFzNw"/>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dRl-860xEeu-2IxxI52J7g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_acu_sK0zEeuvSOVcsXUZdQ" name="T50: Providenciar portaria no boletim ufsc" outgoing="_enVX4K0zEeuvSOVcsXUZdQ _fIhEALKyEeutJdt5dtTumA" incoming="_JJpHQK0zEeuvSOVcsXUZdQ" actor="_jJ680K00EeuvSOVcsXUZdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JJbr4a0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JJbr4K0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JJbr4q0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqnrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqn7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqoLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqobAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemanal" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemanal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqorAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqo7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemanal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqpLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqpbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqprAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqp7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTeoricaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTeoricaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqqLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqqbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTeoricaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqqrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqq7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqrLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqrbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaPraticaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaPraticaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqrrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqr7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaPraticaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqsLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqsbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqsrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqs7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqtLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqtbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqtrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqt7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoquLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqubAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nroPortaria" content="portariaAjusteCurricularInput?.nroPortaria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqurAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqu7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNroPortaria">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqvLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqvbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqvrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqv7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDisciplina" content="portariaAjusteCurricularInput?.codigoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqwLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqwbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqwrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqw7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqxLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqxbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeProReitorGrad" content="portariaAjusteCurricularInput?.nomeProReitorGrad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqxrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqx7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeProReitorGrad">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqyLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqybAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoqyrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoqy7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDepartamento" content="portariaAjusteCurricularInput?.codigoDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoqzLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoqzbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoqzrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoqz7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq0LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq0bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDisciplina" content="portariaAjusteCurricularInput?.nomeDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq0rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq07AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq1LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq1bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq1rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq17AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.descricaoEmenta" content="portariaAjusteCurricularInput?.descricaoEmenta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq2LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq2bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDescricaoEmenta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq2rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq27AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq3LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq3bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDepartamento" content="portariaAjusteCurricularInput?.nomeDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq3rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq37AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq4LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq4bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq4rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq47AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.dataLancamento" content="portariaAjusteCurricularInput?.dataLancamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq5LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq5bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDataLancamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_xYoq5rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_xYoq57AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xYoq6LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_xYoq6bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.assinaturaDigital" content="portariaAjusteCurricularInput?.assinaturaDigital" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xYoq6rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_xYoq67AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setAssinaturaDigital">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3qga0LA7EeuUGry6jKu2kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3qga0bA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4SCU4LA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3qga0rA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput.nroProcessoCriacaoDisciplina" content="portariaAjusteCurricularInput?.nroProcessoCriacaoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9Iu-ELA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3qga07A7EeuUGry6jKu2kw" type="JAVA_METHOD" expression="setNroProcessoCriacaoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JJcS8K0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JJcS8a0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JJcS8q0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JJcS9K0zEeuvSOVcsXUZdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JJcS860zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_acyDB60zEeuvSOVcsXUZdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_US_MYLEnEeuf0e7JypUhFQ" name="formularioPublicacaoPortaria" content="71146179-cf3b-4144-b0d4-c19d1003e971" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_acyDBq0zEeuvSOVcsXUZdQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_xYoqkLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" dataReference="portariaAjusteCurricular" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqkbAvEeutU43AkzFzNw" name="cargaHorariaTotalSemanal" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqkrAvEeutU43AkzFzNw" name="cargaHorariaTeoricaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqk7AvEeutU43AkzFzNw" name="cargaHorariaPraticaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqlLAvEeutU43AkzFzNw" name="cargaHorariaTotalSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqlbAvEeutU43AkzFzNw" name="nroPortaria" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqlrAvEeutU43AkzFzNw" name="codigoDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoql7AvEeutU43AkzFzNw" name="nomeProReitorGrad" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqmLAvEeutU43AkzFzNw" name="codigoDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqmbAvEeutU43AkzFzNw" name="nomeDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqmrAvEeutU43AkzFzNw" name="descricaoEmenta" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqm7AvEeutU43AkzFzNw" name="nomeDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqnLAvEeutU43AkzFzNw" name="dataLancamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_xYoqnbAvEeutU43AkzFzNw" name="assinaturaDigital" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_2yplwLA7EeuUGry6jKu2kw" name="nroProcessoCriacaoDisciplina">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_2yqM0LA7EeuUGry6jKu2kw"/>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_acyDCa0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_enODIK0zEeuvSOVcsXUZdQ" name="Fim1" incoming="_enVX4K0zEeuvSOVcsXUZdQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_enOqMa0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_enOqMK0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_enOqMq0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_5KuosLKyEeutJdt5dtTumA" name="T90: Incluir a informação sobre a portaria no relatório específico" outgoing="_Fe5JALKzEeutJdt5dtTumA" incoming="_HcI40LKzEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5KxE8bKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5KxE8LKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5KxE8rKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5KxE87KyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5KxE9LKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5KxE9bKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5KxE97KyEeutJdt5dtTumA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5KxE9rKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_FIT1ALKzEeutJdt5dtTumA" name="Fim3" incoming="_Fe5JALKzEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FIT1ArKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FIT1AbKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FIT1A7KzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_nPZ6ULKsEeutJdt5dtTumA" name="PRO REITOR DE GRADUACAO" actor="_yPmigK00EeuvSOVcsXUZdQ">
        <elements xmi:type="process:Task" xmi:id="_aH9CgK0zEeuvSOVcsXUZdQ" name="T40: Assinar portaria de ajuste curricular" outgoing="_JJpHQK0zEeuvSOVcsXUZdQ" incoming="_HEc8YK0zEeuvSOVcsXUZdQ" actor="_yPmigK00EeuvSOVcsXUZdQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HDyOAK0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HDxm8K0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HDyOAa0zEeuvSOVcsXUZdQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_3OpbvrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opbv7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpbwLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpbwbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemanal" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemanal" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpbwrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opbw7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemanal">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpbxLAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OpbxbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpbxrAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opbx7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTeoricaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTeoricaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpbyLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OpbybAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTeoricaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpbyrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opby7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpbzLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpbzbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaPraticaSemestral" content="portariaAjusteCurricularInput?.cargaHorariaPraticaSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpbzrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opbz7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaPraticaSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb0LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb0bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb0rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb07AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.cargaHorariaTotalSemestral" content="portariaAjusteCurricularInput?.cargaHorariaTotalSemestral" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb1LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb1bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCargaHorariaTotalSemestral">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb1rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb17AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb2LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb2bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nroPortaria" content="portariaAjusteCurricularInput?.nroPortaria" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb2rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb27AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNroPortaria">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb3LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb3bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb3rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb37AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDisciplina" content="portariaAjusteCurricularInput?.codigoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb4LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb4bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb4rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb47AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb5LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb5bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeProReitorGrad" content="portariaAjusteCurricularInput?.nomeProReitorGrad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb5rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb57AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeProReitorGrad">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb6LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb6bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb6rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb67AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.codigoDepartamento" content="portariaAjusteCurricularInput?.codigoDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb7LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb7bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setCodigoDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb7rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb77AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb8LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb8bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDisciplina" content="portariaAjusteCurricularInput?.nomeDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb8rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb87AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb9LAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb9bAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb9rAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb97AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.descricaoEmenta" content="portariaAjusteCurricularInput?.descricaoEmenta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb-LAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb-bAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDescricaoEmenta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3Opb-rAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3Opb-7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3Opb_LAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3Opb_bAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.nomeDepartamento" content="portariaAjusteCurricularInput?.nomeDepartamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3Opb_rAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3Opb_7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setNomeDepartamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpcALAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OpcAbAvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpcArAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpcA7AvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.dataLancamento" content="portariaAjusteCurricularInput?.dataLancamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpcBLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OpcBbAvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setDataLancamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3OpcBrAvEeutU43AkzFzNw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OpcB7AvEeutU43AkzFzNw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3OpcCLAvEeutU43AkzFzNw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OpcCbAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput.assinaturaDigital" content="portariaAjusteCurricularInput?.assinaturaDigital" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_3OpcCrAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OpcC7AvEeutU43AkzFzNw" type="JAVA_METHOD" expression="setAssinaturaDigital">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_vbYdQLA7EeuUGry6jKu2kw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_vbYdQbA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" content="portariaAjusteCurricular" type="TYPE_VARIABLE" returnType="com.company.model.Portaria">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_vykOMLA7EeuUGry6jKu2kw" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_vbYdQrA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput.nroProcessoCriacaoDisciplina" content="portariaAjusteCurricularInput?.nroProcessoCriacaoDisciplina" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_0Jz7QLA7EeuUGry6jKu2kw" name="portariaAjusteCurricularInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_vbYdQ7A7EeuUGry6jKu2kw" type="JAVA_METHOD" expression="setNroProcessoCriacaoDisciplina">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HDyOAq0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HDyOA60zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HDyOBK0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HDy1EK0zEeuvSOVcsXUZdQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HDyOBa0zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_aH-3sa0zEeuvSOVcsXUZdQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_YmkdYK01EeuvSOVcsXUZdQ" name="formularioAssinaturaPortaria" content="bda36800-1d07-49d5-8a61-c7e0f83f016e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_aH-3sK0zEeuvSOVcsXUZdQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_3OpbsLAvEeutU43AkzFzNw" name="portariaAjusteCurricularInput" type="COMPLEX" dataReference="portariaAjusteCurricular" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbsbAvEeutU43AkzFzNw" name="cargaHorariaTotalSemanal" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbsrAvEeutU43AkzFzNw" name="cargaHorariaTeoricaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3Opbs7AvEeutU43AkzFzNw" name="cargaHorariaPraticaSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbtLAvEeutU43AkzFzNw" name="cargaHorariaTotalSemestral" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbtbAvEeutU43AkzFzNw" name="nroPortaria" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbtrAvEeutU43AkzFzNw" name="codigoDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3Opbt7AvEeutU43AkzFzNw" name="nomeProReitorGrad" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbuLAvEeutU43AkzFzNw" name="codigoDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbubAvEeutU43AkzFzNw" name="nomeDisciplina" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpburAvEeutU43AkzFzNw" name="descricaoEmenta" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3Opbu7AvEeutU43AkzFzNw" name="nomeDepartamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbvLAvEeutU43AkzFzNw" name="dataLancamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_3OpbvbAvEeutU43AkzFzNw" name="assinaturaDigital" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_uGV88LA7EeuUGry6jKu2kw" name="nroProcessoCriacaoDisciplina">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_uGV88bA7EeuUGry6jKu2kw"/>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_aH-3s60zEeuvSOVcsXUZdQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_fIX6ELKyEeutJdt5dtTumA" name="Desvio1" outgoing="_gNmcwLKyEeutJdt5dtTumA _24kY0LKyEeutJdt5dtTumA" incoming="_fIhEALKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fIYhIbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fIYhILKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fIYhIrKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_nlMkILKsEeutJdt5dtTumA" name="SECRETARIA DA PROGRAD" actor="_QfyOILK0EeutJdt5dtTumA">
        <elements xmi:type="process:Activity" xmi:id="_T7HXcLKyEeutJdt5dtTumA" name="T60: Providenciar a organização do arquivamento na portaria" outgoing="_dcMFELKyEeutJdt5dtTumA" incoming="_gNmcwLKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_T7IlkbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_T7IlkLKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_T7IlkrKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_T7Ilk7KyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_T7IllLKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_T7IllbKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_T7Ill7KyEeutJdt5dtTumA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_T7IllrKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_dFVrULKyEeutJdt5dtTumA" name="Fim2" incoming="_dcMFELKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dFWSYbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dFWSYLKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dFWSYrKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_nyn8ILKsEeutJdt5dtTumA" name="GABINETE DA REITORIA" actor="_QfyOILK0EeutJdt5dtTumA">
        <elements xmi:type="process:Activity" xmi:id="_qVO0ELKyEeutJdt5dtTumA" name="T70: Publicar a portaria" outgoing="_161lQLKyEeutJdt5dtTumA" incoming="_24kY0LKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qVPbIbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qVPbILKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qVPbIrKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qVPbI7KyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qVPbJLKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qVPbJbKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qVPbJ7KyEeutJdt5dtTumA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qVPbJrKyEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateThrowSignalEvent" xmi:id="_1NGVgLKyEeutJdt5dtTumA" name="Sinal1" signalCode="send_signal_ajuste_curricular_pronto" outgoing="_3qV0ALKyEeutJdt5dtTumA" incoming="_161lQLKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1NG8kbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1NG8kLKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1NG8krKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_3qTXwLKyEeutJdt5dtTumA" name="Desvio2" outgoing="_HcI40LKzEeutJdt5dtTumA _MsrlYLKzEeutJdt5dtTumA" incoming="_3qV0ALKyEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3qTXwrKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3qTXwbKyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3qTXw7KyEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_n-tQULKsEeutJdt5dtTumA" name="SECRETARIAS DOS CURSOS" actor="_QfyOILK0EeutJdt5dtTumA">
        <elements xmi:type="process:Activity" xmi:id="_JTrCMLKzEeutJdt5dtTumA" name="T80: Incluir disciplina no curriculo" outgoing="_NugOwLKzEeutJdt5dtTumA" incoming="_MsrlYLKzEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JTrpQbKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JTrpQLKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JTrpQrKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JTrpQ7KzEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JTrpRLKzEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JTrpRbKzEeutJdt5dtTumA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JTrpR7KzEeutJdt5dtTumA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JTrpRrKzEeutJdt5dtTumA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_NXFNQLKzEeutJdt5dtTumA" name="Fim4" incoming="_NugOwLKzEeutJdt5dtTumA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NXFNQrKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NXFNQbKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NXF0ULKzEeutJdt5dtTumA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_9Cy_UK00EeuvSOVcsXUZdQ" name="portariaAjusteCurricular" dataType="_dRl_FK0xEeu-2IxxI52J7g" className="com.company.model.Portaria">
        <defaultValue xmi:type="expression:Expression" xmi:id="_9Cy_Ua00EeuvSOVcsXUZdQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_dRl-9K0xEeu-2IxxI52J7g">
        <targetForm xmi:type="expression:Expression" xmi:id="_-sBRkLKzEeutJdt5dtTumA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_dRl-9q0xEeu-2IxxI52J7g">
        <targetForm xmi:type="expression:Expression" xmi:id="_dRl-960xEeu-2IxxI52J7g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HEc8YK0zEeuvSOVcsXUZdQ" target="_aH9CgK0zEeuvSOVcsXUZdQ" source="_dRl-560xEeu-2IxxI52J7g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HEdjcK0zEeuvSOVcsXUZdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HEdjca0zEeuvSOVcsXUZdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JJpHQK0zEeuvSOVcsXUZdQ" target="_acu_sK0zEeuvSOVcsXUZdQ" source="_aH9CgK0zEeuvSOVcsXUZdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JJpHQa0zEeuvSOVcsXUZdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_JJpuUK0zEeuvSOVcsXUZdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_enVX4K0zEeuvSOVcsXUZdQ" target="_enODIK0zEeuvSOVcsXUZdQ" source="_acu_sK0zEeuvSOVcsXUZdQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_enV-8K0zEeuvSOVcsXUZdQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_enV-8a0zEeuvSOVcsXUZdQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wTSY0LKwEeutJdt5dtTumA" target="_q6nD8LKwEeutJdt5dtTumA" source="_dRl-460xEeu-2IxxI52J7g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wTS_4LKwEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_wTS_4bKwEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G2228LKyEeutJdt5dtTumA" target="_Gc5e0LKyEeutJdt5dtTumA" source="_q6nD8LKwEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G2228bKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_G2228rKyEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_H0zs8LKyEeutJdt5dtTumA" target="_dRl-560xEeu-2IxxI52J7g" source="_Gc5e0LKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_H0zs8bKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_H0zs8rKyEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dcMFELKyEeutJdt5dtTumA" target="_dFVrULKyEeutJdt5dtTumA" source="_T7HXcLKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dcMFEbKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dcMFErKyEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fIhEALKyEeutJdt5dtTumA" target="_fIX6ELKyEeutJdt5dtTumA" source="_acu_sK0zEeuvSOVcsXUZdQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fIhrELKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_fIhrEbKyEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gNmcwLKyEeutJdt5dtTumA" target="_T7HXcLKyEeutJdt5dtTumA" source="_fIX6ELKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gNnD0LKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_gNnD0bKyEeutJdt5dtTumA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_161lQLKyEeutJdt5dtTumA" target="_1NGVgLKyEeutJdt5dtTumA" source="_qVO0ELKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_161lQbKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_161lQrKyEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_24kY0LKyEeutJdt5dtTumA" target="_qVO0ELKyEeutJdt5dtTumA" source="_fIX6ELKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_24kY0bKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_24kY0rKyEeutJdt5dtTumA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3qV0ALKyEeutJdt5dtTumA" target="_3qTXwLKyEeutJdt5dtTumA" source="_1NGVgLKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3qV0AbKyEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3qV0ArKyEeutJdt5dtTumA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Fe5JALKzEeutJdt5dtTumA" target="_FIT1ALKzEeutJdt5dtTumA" source="_5KuosLKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Fe5JAbKzEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Fe5JArKzEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HcI40LKzEeutJdt5dtTumA" target="_5KuosLKyEeutJdt5dtTumA" source="_3qTXwLKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HcI40bKzEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HcI40rKzEeutJdt5dtTumA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MsrlYLKzEeutJdt5dtTumA" target="_JTrCMLKzEeutJdt5dtTumA" source="_3qTXwLKyEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MsrlYbKzEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_MsrlYrKzEeutJdt5dtTumA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NugOwLKzEeutJdt5dtTumA" target="_NXFNQLKzEeutJdt5dtTumA" source="_JTrCMLKzEeutJdt5dtTumA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NugOwbKzEeutJdt5dtTumA"/>
        <condition xmi:type="expression:Expression" xmi:id="_NugOwrKzEeutJdt5dtTumA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_jJ680K00EeuvSOVcsXUZdQ" documentation="Técnico em Exercício no DEN PROGRAD" name="tecnico-exercicio-den-prograd" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_yPmigK00EeuvSOVcsXUZdQ" documentation="Pró reitor de graduação" name="pro-reitor-de-graduacao"/>
      <actors xmi:type="process:Actor" xmi:id="_QfyOILK0EeutJdt5dtTumA" documentation="default" name="default"/>
      <contract xmi:type="process:Contract" xmi:id="_dRl-_K0xEeu-2IxxI52J7g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl-_a0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl-_q0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl-_60xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_AK0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_Aa0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_Aq0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_A60xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_BK0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_Ba0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_Bq0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_B60xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_CK0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dRl_Ca0xEeu-2IxxI52J7g">
        <name xmi:type="expression:Expression" xmi:id="_dRl_Cq0xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dRl_C60xEeu-2IxxI52J7g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_dRl_DK0xEeu-2IxxI52J7g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_dRl_Da0xEeu-2IxxI52J7g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_dRl_Dq0xEeu-2IxxI52J7g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_dRl_D60xEeu-2IxxI52J7g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_dRl_EK0xEeu-2IxxI52J7g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_dRl_Ea0xEeu-2IxxI52J7g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_dRl_Eq0xEeu-2IxxI52J7g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_dRl_E60xEeu-2IxxI52J7g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_dRl_FK0xEeu-2IxxI52J7g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_dRl_Fa0xEeu-2IxxI52J7g" type="Process" element="_dRl-4K0xEeu-2IxxI52J7g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_dRl_Fq0xEeu-2IxxI52J7g" type="2007" element="_dRl-4a0xEeu-2IxxI52J7g">
      <children xmi:type="notation:DecorationNode" xmi:id="_dRl_F60xEeu-2IxxI52J7g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_dRl_GK0xEeu-2IxxI52J7g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_dRl_Ga0xEeu-2IxxI52J7g" type="3007" element="_dRl-4q0xEeu-2IxxI52J7g">
          <children xmi:type="notation:DecorationNode" xmi:id="_dRl_Gq0xEeu-2IxxI52J7g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_dRl_G60xEeu-2IxxI52J7g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_dRl_H60xEeu-2IxxI52J7g" type="3002" element="_dRl-460xEeu-2IxxI52J7g" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_dRl_IK0xEeu-2IxxI52J7g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dRl_Ia0xEeu-2IxxI52J7g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_Iq0xEeu-2IxxI52J7g" x="61" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_q6oSELKwEeutJdt5dtTumA" type="3006" element="_q6nD8LKwEeutJdt5dtTumA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_q6oSErKwEeutJdt5dtTumA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_q6oSEbKwEeutJdt5dtTumA" x="175" y="104" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Gc9wQLKyEeutJdt5dtTumA" type="3006" element="_Gc5e0LKyEeutJdt5dtTumA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Gc9wQrKyEeutJdt5dtTumA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gc9wQbKyEeutJdt5dtTumA" x="549" y="128" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_dRl_I60xEeu-2IxxI52J7g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_dRl_JK0xEeu-2IxxI52J7g" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_dRl_Ja0xEeu-2IxxI52J7g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_dRl_Jq0xEeu-2IxxI52J7g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_J60xEeu-2IxxI52J7g" x="48" y="10" width="1516" height="282"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Cl5GYK0zEeuvSOVcsXUZdQ" type="3007" element="_ClmygK0zEeuvSOVcsXUZdQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Cl6UgK0zEeuvSOVcsXUZdQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Cl6Uga0zEeuvSOVcsXUZdQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_dRl_HK0xEeu-2IxxI52J7g" type="3005" element="_dRl-560xEeu-2IxxI52J7g" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dRl_Ha0xEeu-2IxxI52J7g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_Hq0xEeu-2IxxI52J7g" x="80" y="52" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ac0fQK0zEeuvSOVcsXUZdQ" type="3005" element="_acu_sK0zEeuvSOVcsXUZdQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ac1GUK0zEeuvSOVcsXUZdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ac0fQa0zEeuvSOVcsXUZdQ" x="498" y="86" width="141" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_enPRQK0zEeuvSOVcsXUZdQ" type="3003" element="_enODIK0zEeuvSOVcsXUZdQ" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_enPRQq0zEeuvSOVcsXUZdQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_enPRQ60zEeuvSOVcsXUZdQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_enPRQa0zEeuvSOVcsXUZdQ" x="802" y="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5KyTELKyEeutJdt5dtTumA" type="3006" element="_5KuosLKyEeutJdt5dtTumA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5Ky6ILKyEeutJdt5dtTumA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5KyTEbKyEeutJdt5dtTumA" x="1033" y="163" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FIVDILKzEeutJdt5dtTumA" type="3003" element="_FIT1ALKzEeutJdt5dtTumA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_FIVDIrKzEeutJdt5dtTumA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_FIVDI7KzEeutJdt5dtTumA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FIVDIbKzEeutJdt5dtTumA" x="1317" y="174"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Cl5tcK0zEeuvSOVcsXUZdQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Cl5tca0zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Cl5tcq0zEeuvSOVcsXUZdQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Cl67kK0zEeuvSOVcsXUZdQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Cl5tc60zEeuvSOVcsXUZdQ" x="48" y="282" width="1516" height="283"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_nPbIcLKsEeutJdt5dtTumA" type="3007" element="_nPZ6ULKsEeutJdt5dtTumA">
          <children xmi:type="notation:DecorationNode" xmi:id="_nPbIdbKsEeutJdt5dtTumA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nPbIdrKsEeutJdt5dtTumA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_aIAs4K0zEeuvSOVcsXUZdQ" type="3005" element="_aH9CgK0zEeuvSOVcsXUZdQ" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_aIBT8K0zEeuvSOVcsXUZdQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aIAs4a0zEeuvSOVcsXUZdQ" x="90" y="34" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fIYhI7KyEeutJdt5dtTumA" type="3009" element="_fIX6ELKyEeutJdt5dtTumA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_fIZIMLKyEeutJdt5dtTumA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fIZIMbKyEeutJdt5dtTumA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fIYhJLKyEeutJdt5dtTumA" x="555" y="74"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nPbIcbKsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nPbIcrKsEeutJdt5dtTumA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nPbIc7KsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nPbId7KsEeutJdt5dtTumA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nPbIdLKsEeutJdt5dtTumA" x="48" y="493" width="1516" height="196"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_nlNyQLKsEeutJdt5dtTumA" type="3007" element="_nlMkILKsEeutJdt5dtTumA">
          <children xmi:type="notation:DecorationNode" xmi:id="_nlNyRbKsEeutJdt5dtTumA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nlOZULKsEeutJdt5dtTumA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_T7JzsLKyEeutJdt5dtTumA" type="3006" element="_T7HXcLKyEeutJdt5dtTumA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_T7JzsrKyEeutJdt5dtTumA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_T7JzsbKyEeutJdt5dtTumA" x="175" y="85" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dFXggLKyEeutJdt5dtTumA" type="3003" element="_dFVrULKyEeutJdt5dtTumA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_dFYHkLKyEeutJdt5dtTumA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dFYHkbKyEeutJdt5dtTumA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dFXggbKyEeutJdt5dtTumA" x="408" y="102"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nlNyQbKsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nlNyQrKsEeutJdt5dtTumA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nlNyQ7KsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nlOZUbKsEeutJdt5dtTumA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nlNyRLKsEeutJdt5dtTumA" x="48" y="721" width="1516" height="205"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_nypxULKsEeutJdt5dtTumA" type="3007" element="_nyn8ILKsEeutJdt5dtTumA">
          <children xmi:type="notation:DecorationNode" xmi:id="_nyqYYLKsEeutJdt5dtTumA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nyqYYbKsEeutJdt5dtTumA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qVPbKLKyEeutJdt5dtTumA" type="3006" element="_qVO0ELKyEeutJdt5dtTumA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qVQCMbKyEeutJdt5dtTumA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qVQCMLKyEeutJdt5dtTumA" x="650" y="49" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1NIKsLKyEeutJdt5dtTumA" type="3022" element="_1NGVgLKyEeutJdt5dtTumA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_1NIKsrKyEeutJdt5dtTumA" type="5037">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1NIKs7KyEeutJdt5dtTumA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1NIKsbKyEeutJdt5dtTumA" x="906" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3qT-0LKyEeutJdt5dtTumA" type="3009" element="_3qTXwLKyEeutJdt5dtTumA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_3qT-0rKyEeutJdt5dtTumA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3qT-07KyEeutJdt5dtTumA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3qT-0bKyEeutJdt5dtTumA" x="1061" y="73"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nypxUbKsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nypxUrKsEeutJdt5dtTumA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nypxU7KsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nyqYYrKsEeutJdt5dtTumA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nypxVLKsEeutJdt5dtTumA" x="48" y="966" width="1516" height="183"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_n-uecLKsEeutJdt5dtTumA" type="3007" element="_n-tQULKsEeutJdt5dtTumA">
          <children xmi:type="notation:DecorationNode" xmi:id="_n-vskLKsEeutJdt5dtTumA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_n-vskbKsEeutJdt5dtTumA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_JTrpSLKzEeutJdt5dtTumA" type="3006" element="_JTrCMLKzEeutJdt5dtTumA" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JTrpSrKzEeutJdt5dtTumA" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JTrpSbKzEeutJdt5dtTumA" x="1107" y="25" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NXHCcLKzEeutJdt5dtTumA" type="3003" element="_NXFNQLKzEeutJdt5dtTumA" fontName="Ubuntu">
              <children xmi:type="notation:DecorationNode" xmi:id="_NXHCcrKzEeutJdt5dtTumA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NXHCc7KzEeutJdt5dtTumA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NXHCcbKzEeutJdt5dtTumA" x="1304" y="23"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_n-vFgLKsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_n-vFgbKsEeutJdt5dtTumA" fontName="Ubuntu"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_n-vFgrKsEeutJdt5dtTumA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_n-vskrKsEeutJdt5dtTumA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n-vFg7KsEeutJdt5dtTumA" x="48" y="1149" width="1516" height="190"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_dRl_KK0xEeu-2IxxI52J7g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_dRl_Ka0xEeu-2IxxI52J7g" fontName="Ubuntu"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_dRl_Kq0xEeu-2IxxI52J7g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_dRl_K60xEeu-2IxxI52J7g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dRl_LK0xEeu-2IxxI52J7g" width="1539" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_dRl_La0xEeu-2IxxI52J7g"/>
    <edges xmi:type="notation:Connector" xmi:id="_HEfYoK0zEeuvSOVcsXUZdQ" type="4001" element="_HEc8YK0zEeuvSOVcsXUZdQ" source="_dRl_HK0xEeu-2IxxI52J7g" target="_aIAs4K0zEeuvSOVcsXUZdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HEf_sK0zEeuvSOVcsXUZdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HEf_sa0zEeuvSOVcsXUZdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HEfYoa0zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HEfYoq0zEeuvSOVcsXUZdQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JJq8cK0zEeuvSOVcsXUZdQ" type="4001" element="_JJpHQK0zEeuvSOVcsXUZdQ" source="_aIAs4K0zEeuvSOVcsXUZdQ" target="_ac0fQK0zEeuvSOVcsXUZdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JJrjgK0zEeuvSOVcsXUZdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JJrjga0zEeuvSOVcsXUZdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JJq8ca0zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JJq8cq0zEeuvSOVcsXUZdQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_enV-8q0zEeuvSOVcsXUZdQ" type="4001" element="_enVX4K0zEeuvSOVcsXUZdQ" source="_ac0fQK0zEeuvSOVcsXUZdQ" target="_enPRQK0zEeuvSOVcsXUZdQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_enWmAK0zEeuvSOVcsXUZdQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_enWmAa0zEeuvSOVcsXUZdQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_enV-860zEeuvSOVcsXUZdQ" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_enV-9K0zEeuvSOVcsXUZdQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wTU1ELKwEeutJdt5dtTumA" type="4001" element="_wTSY0LKwEeutJdt5dtTumA" source="_dRl_H60xEeu-2IxxI52J7g" target="_q6oSELKwEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wTVcILKwEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wTVcIbKwEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wTU1EbKwEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wTU1ErKwEeutJdt5dtTumA" points="[-6, -2, -97, -51]$[98, 20, 7, -29]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wTZtkLKwEeutJdt5dtTumA" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G23eALKyEeutJdt5dtTumA" type="4001" element="_G2228LKyEeutJdt5dtTumA" source="_q6oSELKwEeutJdt5dtTumA" target="_Gc9wQLKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G23eA7KyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G23eBLKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G23eAbKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G23eArKyEeutJdt5dtTumA" points="[0, 0, -271, -22]$[321, 15, 50, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G24sILKyEeutJdt5dtTumA" id="(1.0,0.35526315789473684)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_H00UALKyEeutJdt5dtTumA" type="4001" element="_H0zs8LKyEeutJdt5dtTumA" source="_Gc9wQLKyEeutJdt5dtTumA" target="_dRl_HK0xEeu-2IxxI52J7g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_H00UA7KyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_H00UBLKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_H00UAbKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_H00UArKyEeutJdt5dtTumA" points="[-51, 26, 392, -206]$[-446, 203, -3, -29]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_H01iILKyEeutJdt5dtTumA" id="(1.0,0.48)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dcMsILKyEeutJdt5dtTumA" type="4001" element="_dcMFELKyEeutJdt5dtTumA" source="_T7JzsLKyEeutJdt5dtTumA" target="_dFXggLKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dcMsI7KyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dcMsJLKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dcMsIbKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dcMsIrKyEeutJdt5dtTumA" points="[0, 5, -97, 0]$[93, 5, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dcOhULKyEeutJdt5dtTumA" id="(1.0,0.38571428571428573)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dcOhUbKyEeutJdt5dtTumA" id="(0.13333333333333333,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fIhrErKyEeutJdt5dtTumA" type="4001" element="_fIhEALKyEeutJdt5dtTumA" source="_ac0fQK0zEeuvSOVcsXUZdQ" target="_fIYhI7KyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fIhrFbKyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fIhrFrKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fIhrE7KyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fIhrFLKyEeutJdt5dtTumA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gNnq4LKyEeutJdt5dtTumA" type="4001" element="_gNmcwLKyEeutJdt5dtTumA" source="_fIYhI7KyEeutJdt5dtTumA" target="_T7JzsLKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gNoR8LKyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gNoR8bKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gNnq4bKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gNnq4rKyEeutJdt5dtTumA" points="[-35, -3, 318, -212]$[-345, 244, 8, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gNquMLKyEeutJdt5dtTumA" id="(1.0,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_162zYLKyEeutJdt5dtTumA" type="4001" element="_161lQLKyEeutJdt5dtTumA" source="_qVPbKLKyEeutJdt5dtTumA" target="_1NIKsLKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_162zY7KyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_163acLKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_162zYbKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_162zYrKyEeutJdt5dtTumA" points="[0, 8, -151, 1]$[147, 21, -4, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1652sLKyEeutJdt5dtTumA" id="(1.0,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_24k_4LKyEeutJdt5dtTumA" type="4001" element="_24kY0LKyEeutJdt5dtTumA" source="_fIYhI7KyEeutJdt5dtTumA" target="_qVPbKLKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_24lm8LKyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_24lm8bKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_24k_4bKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_24k_4rKyEeutJdt5dtTumA" points="[-2, -6, -114, -384]$[172, 372, 60, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_24oDMLKyEeutJdt5dtTumA" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3qWbELKyEeutJdt5dtTumA" type="4001" element="_3qV0ALKyEeutJdt5dtTumA" source="_1NIKsLKyEeutJdt5dtTumA" target="_3qT-0LKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3qWbE7KyEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3qWbFLKyEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3qWbEbKyEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3qWbErKyEeutJdt5dtTumA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Fe5wELKzEeutJdt5dtTumA" type="4001" element="_Fe5JALKzEeutJdt5dtTumA" source="_5KyTELKyEeutJdt5dtTumA" target="_FIVDILKzEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Fe9acLKzEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Fe9acbKzEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Fe5wEbKzEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Fe5wErKzEeutJdt5dtTumA" points="[0, -6, -127, 0]$[124, -7, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Fe-BgLKzEeutJdt5dtTumA" id="(1.0,0.35)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Fe-okLKzEeutJdt5dtTumA" id="(0.1,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HcKG8LKzEeutJdt5dtTumA" type="4001" element="_HcI40LKzEeutJdt5dtTumA" source="_3qT-0LKyEeutJdt5dtTumA" target="_5KyTELKyEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HcKG87KzEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HcKG9LKzEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HcKG8bKzEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HcKG8rKzEeutJdt5dtTumA" points="[-1, -9, -10, 574]$[-71, -583, -80, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HcNxULKzEeutJdt5dtTumA" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MsszgLKzEeutJdt5dtTumA" type="4001" element="_MsrlYLKzEeutJdt5dtTumA" source="_3qT-0LKyEeutJdt5dtTumA" target="_JTrpSLKzEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MstakLKzEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MstakbKzEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MsszgbKzEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MsszgrKzEeutJdt5dtTumA" points="[-2, -3, -65, -117]$[65, 144, 2, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ms6O4LKzEeutJdt5dtTumA" id="(1.0,0.5813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Nug10LKzEeutJdt5dtTumA" type="4001" element="_NugOwLKzEeutJdt5dtTumA" source="_JTrpSLKzEeutJdt5dtTumA" target="_NXHCcLKzEeutJdt5dtTumA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Nug107KzEeutJdt5dtTumA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Nug11LKzEeutJdt5dtTumA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Nug10bKzEeutJdt5dtTumA" fontName="Ubuntu"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Nug10rKzEeutJdt5dtTumA" points="[0, 0, -80, 21]$[78, -22, -2, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NuiD8LKzEeutJdt5dtTumA" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NuiD8bKzEeutJdt5dtTumA" id="(0.1,0.3)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
